apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-yaml
    method: fromcode
    test: newlabel
  name: nginx-yaml
spec:
  containers:
  - image: nginx
    name: nginx-yaml
  dnsPolicy: ClusterFirst
  restartPolicy: Always
